import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

export const metadata: Metadata = {
  title: "Ecommerce Frontend",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <body>
          <Header></Header>
          {children}
          <Footer></Footer>
      </body>
    </html>
  );
}
