import "./globals.css";
import type { Metadata } from "next";
import ReduxProvider from "../store/ReduxProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Ecommerce Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
  <body>
        <ReduxProvider>{children}</ReduxProvider>
          <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
